{% set version = "5.2.2" %}
{% set number = "2" %}
{% set cuda_enabled = cuda_compiler_version is not undefined and cuda_compiler_version == '9.2' %}
{% set build_ext_version = "1.0.0" %}
{% set build_ext = "cuda" if cuda_enabled else "cpu" %}
{% set build_string = "h{}_{}_{}".format(PKG_HASH, number, build_ext) %}

package:
  name: omniscidb
  version: {{ version }}

source:
  path: ~/omniscidb
  #url: https://github.com/omnisci/omniscidb/archive/v{{ version }}.tar.gz
  #sha256: 7587ee6dfd900dc23b1ba1f6357c94bf65a997a25e21ee364b3e5d871dddd6fc
  patches:
    - skip-boost-libs-install.patch

build:
  number: {{ number }}
  string: "{{ build_string }}"
  skip: true  # [cuda_compiler_version not in (undefined, "None", "9.2")]
  skip: true  # [not linux64]
  missing_dso_whitelist:
    - "*/libcuda.*"  # [cuda_compiler_version not in (undefined, "None")]
  track_features:
    {{ "- arrow-cuda" if cuda_enabled else "" }}

requirements:
  build:
    - {{ compiler('cgo') }}
    - {{ compiler('cxx') }}
    - {{ compiler("cuda") }}  # [cuda_compiler_version not in (undefined, "None")]
    # omniscidb <=5.2.2 is not llvm 10+ ready
    - clangdev
    # clang++ is used for generating the bytecodes of extension functions
    - clangxx
    - cmake
    - llvmdev 9
    - make
    - maven
    - cython
    - numpy =1.18.5
    - pyarrow =0.16  
  host:
    # omniscidb <=5.2.2 is not arrow-cpp 0.17+ ready
    - arrow-cpp =0.16.*=*{{ build_ext }}
    - bisonpp
    - blosc
    - boost-cpp
    - clangdev
    - double-conversion
    - flex
    - gflags
    - glog
    - llvmdev 9
    - llvm
    - libarchive
    - libgdal
    - libkml
    - libpng
    # for some reason, librdkafka 1.4+ triggers dependency conflicts
    - librdkafka <1.4
    - ncurses
    - openldap
    - openssl
    - snappy
    - tbb-devel
    - thrift-cpp
  run:
    - boost-cpp
    - bzip2
    # omnscidb Load-time UDF support calls clang++
    - gxx_{{ target_platform }}
    - ncurses
    - openjdk 8
    - xz
    - zlib
  run_constrained:
    - arrow-cpp-proc * {{ build_ext }}
    - cudatoolkit >=9.2  # [cuda_compiler_version not in (undefined, "None")]

test:
  commands:
    - omnisql -v
    - which omnisci_server

about:
  home: https://www.omnisci.com/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.md
  summary: 'The OmniSci database'

  description: |
    OmniSciDB is an in-memory, column store, SQL relational database
    that was designed from the ground up to run on GPUs.

    This recipe provides both CUDA enabled and CUDA disabled omniscidb
    packages.
  doc_url: https://www.omnisci.com/docs/latest/
  dev_url: https://github.com/omnisci/omniscidb

extra:
  recipe-maintainers:
    - xmnlab
    - pearu
    - andrewseidl
